<?php
session_start();
set_include_path(get_include_path().PATH_SEPARATOR.'../libs/');


if (isset ($_SESSION['recording']) === false) {
        include_once 'nofile.php';
        die();
}

$doc = $_SESSION['recording'];

include 'PHPExcel.php';                         
include 'PHPExcel/Writer/Excel5.php'; 
  
$objPHPExcel = new PHPExcel();                  
$objPHPExcel->getProperties()->setCreator("CARI VOIP system");
$objPHPExcel->getProperties()->setLastModifiedBy("CARI VOIP system");
$objPHPExcel->getProperties()->setTitle('录音记录'); 
$objPHPExcel->getProperties()->setSubject('录音记录');
$objPHPExcel->getProperties()->setDescription('recordings generated by CARI VOIP system');
$objPHPExcel->getProperties()->setKeywords('录音记录');
$objPHPExcel->getProperties()->setCategory('录音记录');
                                                        
$objPHPExcel->setActiveSheetIndex(0);  

        $objPHPExcel->getActiveSheet()->setCellValue('A1','用户');
        $objPHPExcel->getActiveSheet()->setCellValue('B1','号码');
        $objPHPExcel->getActiveSheet()->setCellValue('C1','被叫');
        $objPHPExcel->getActiveSheet()->setCellValue('D1','通话开始时间');
        $objPHPExcel->getActiveSheet()->setCellValue('E1','格式');
	$objPHPExcel->getActiveSheet()->setCellValue('F1','长度');

$rowIdx = 2;
foreach($doc as $row=>$cols){   
                 
        $objPHPExcel->getActiveSheet()->setCellValue('A'.$rowIdx,$cols[0]);
        $objPHPExcel->getActiveSheet()->setCellValue('B'.$rowIdx,$cols[1]);
        $objPHPExcel->getActiveSheet()->setCellValue('C'.$rowIdx,$cols[2]);
        $objPHPExcel->getActiveSheet()->setCellValue('D'.$rowIdx,$cols[3]);
        $objPHPExcel->getActiveSheet()->setCellValue('E'.$rowIdx,$cols[4]);
        $objPHPExcel->getActiveSheet()->setCellValue('F'.$rowIdx,$cols[5]);

	$rowIdx++;
}
$randToken = md5(uniqid(rand(), true));
$xlsfile = "../output/recording${randToken}.xls";
$objPHPExcel->getActiveSheet()->setTitle("录音记录");

$objPHPExcel->setActiveSheetIndex(0);
$objWriter = new PHPExcel_Writer_Excel5($objPHPExcel);
$objWriter->save($xlsfile);
//header("Location: $xlsfile");
//require 'passfile.php';

if(!is_file($xlsfile)){
	include_once 'nofile.php';
	die();
} 
if(!is_readable($xlsfile)){
	include_once 'nofile.php';
}
else{
	require 'passfile.php';
	passfile($xlsfile,'records.xls','xls',true);     
}
     unlink($xlsFile);
?>
